###default path
GET http://localhost:8000/fleetmanagement
###
GET http://localhost:8000/bookingoffers/9
###
POST http://localhost:8000/bookingoffers
Content-Type: application/json{
  "vehicle_id": "name",
  "offer_id": 1,
  "discount": 10,
  "status": "active",
  "booking_id": 9
}
###
PUT http://localhost:8000/bookingoffers/20
Content-Type: application/json

{
  "status": "inactive"
}
###
GET http://localhost:8000/bookings
###
POST http://localhost:8000/bookings
Content-Type: application/json

{
  "booking_id": 9,
  "user_id": 2,
  "vehicle_id": 2,
  "status": "cancelled",
  "total_cost": 1500,
  "payment_id": "SB123",
  "location_id": 2
}
###
POST http://localhost:8000/bookings
Content-Type: application/json

{
  "user_id": 3,
  "vehicle_id": 5,
  "total_cost": 1000,
  "payment_id": "SB32W",
  "location_id": 1

}
###
PUT http://localhost:8000/bookings/8
Content-Type: application/json

{
  "status": "approved"
  }
###
DELETE http://localhost:8000/vehicles/123
###get user
GET http://localhost:8000/users
###create a new user

POST http://localhost:8000/users
Content-Type: application/json

{
  "full_name": "John Doe",
  "contact_phone": "1234567890",
  "email": "johndoe@example.com",
  "address":"maua"
}

###update user information

PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "full_name": "antony",
    "email": "ANTONY@GMAIL",
    "contact_phone": 799919291
  }

###delete users details
  DELETE http://localhost:8000/users/21

###register
POST   http://localhost:8000/auth/register
Content-Type: application/json

{
     "full_name": "gichuki anthony gatitu",
    "username": "antohsnizzah",
    "contact_phone": "1234567890",
     "email": "antohsnizzah@gmail.com",
    "password": "antohsnizzah",
    "address":"maua",
    "role": "admin"
  }

###login~~
POST   http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "antohsnizzah",
    "password": "2a726b8a-1438-4d"
}

###
GET http://localhost:8000/locationbranches
###

GET http://localhost:8000/payments/54

###
POST https://car-api-80da.onrender.com/payments
Content-Type: application/json

{  
   "booking_id": "9",
  "user_id": 7,
  "payment_method": "mpesa",
  "amount": 1000,
  "status": "pending"
}
###
POST http://localhost:8000/auth/reset-password
Content-Type: application/json

{
  "email": "antohsnizzah@gmail.com"
}
###
POST http://localhost:8000/auth/resetting-password
Content-Type: application/json

{
  "token": "a8129f96-b837-4891-a6e6-087bb2c395ef",
  "newPassword": "2a726b8a-1438-4d"
}
###
POST http://localhost:8000/payments
Content-Type: application/json

{
  "booking_id": 54,
  "user_id": 7,
  "payment_method": "mpesa",
  "amount": 1000,
  "status": "pending"
}